spring:
#  cloud:
#    nacos:
#      server-addr: 10.22.82.101:8848
  datasource:
    url: jdbc:mysql:///cloud-mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
  application:
    name: cloud-alibaba-goods
dubbo:
  scan:
    base-packages: cn.icodening.mall.service
logging:
  config: ${loggingConfig:classpath:log4j2.xml}