spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql:///cloud-mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: false
    database: mysql
    generate-ddl: true
  application:
    name: mall-goods
logging:
  level:
    cn.icodening.mall: debug
server:
  port: 30000
